# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Don
tagline:             'Yet another blog'
description:         "Un espace où je pourrais enfin prendre en note ce que je cherche un jour mais que j'oublie toujours le lendemain"
url:                 http://jgaret.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Julien GARET
  url:               http://blog.garet.info
  email:             julien@garet.info

# Custom vars
version:             1.0.0
